// WordArt Constants - MS Office Style WordArt with advanced effects
export const TEXT_STYLES = {
  // Text Transform Styles
  TRANSFORMS: {
    straight: 'straight',
    arch: 'arch',
    archUp: 'archUp',
    archDown: 'archDown',
    curve: 'curve',
    curveUp: 'curveUp',
    curveDown: 'curveDown',
    wave: 'wave',
    waveUp: 'waveUp',
    waveDown: 'waveDown',
    waveDouble: 'waveDouble',
    inflate: 'inflate',
    deflate: 'deflate',
    slant: 'slant',
    squeeze: 'squeeze',
    skewUp: 'skewUp',
    skewDown: 'skewDown',
    circles: 'circles',
    diamond: 'diamond',
    triangle: 'triangle',
    zigzag: 'zigzag',
    bounce: 'bounce',
    spiral: 'spiral',
    helix: 'helix',
  },

  // Fill Colors & Gradients
  FILL_TYPES: {
    solidColor: 'solidColor',
    gradient: 'gradient',
    gradientToOutline: 'gradientToOutline',
    pattern: 'pattern',
    texture: 'texture',
  },

  // Outline Styles
  OUTLINE_STYLES: {
    none: 'none',
    solid: 'solid',
    dashed: 'dashed',
    dotted: 'dotted',
    dashedDot: 'dashedDot',
  },

  // Shadow Effects
  SHADOW_TYPES: {
    none: 'none',
    offset: 'offset',
    perspective: 'perspective',
    perspectiveLeft: 'perspectiveLeft',
    perspectiveRight: 'perspectiveRight',
  },

  // Glow Effects
  GLOW_INTENSITY: {
    none: 0,
    subtle: 4,
    moderate: 8,
    intense: 12,
    extreme: 16,
  },

  // 3D Effects
  BEVEL_TYPES: {
    none: 'none',
    circle: 'circle',
    relaxedInset: 'relaxedInset',
    cross: 'cross',
    angleUp: 'angleUp',
    angleDown: 'angleDown',
    softRound: 'softRound',
    convex: 'convex',
  },

  // Reflection
  REFLECTION_TYPES: {
    none: 'none',
    tight: 'tight',
    loose: 'loose',
    full: 'full',
  },
};

export const TEXT_PRESETS = {
  neon: {
    fillColor: '#00FF00',
    outlineColor: '#FFFFFF',
    outlineWidth: 2,
    glowIntensity: 12,
    transform: 'straight',
    shadow: 'none',
  },
  fire: {
    fillColor: '#FF6600',
    gradientColor: '#FF0000',
    outlineColor: '#FFCC00',
    outlineWidth: 1,
    glowIntensity: 10,
    transform: 'wave',
    shadow: 'offset',
  },
  ice: {
    fillColor: '#00CCFF',
    gradientColor: '#0099FF',
    outlineColor: '#FFFFFF',
    outlineWidth: 2,
    glowIntensity: 8,
    transform: 'curve',
    shadow: 'perspective',
  },
  gold: {
    fillColor: '#FFD700',
    gradientColor: '#FFA500',
    outlineColor: '#8B4513',
    outlineWidth: 2,
    glowIntensity: 6,
    transform: 'straight',
    shadow: 'offset',
    bevel: 'softRound',
  },
  shadow: {
    fillColor: '#333333',
    outlineColor: '#666666',
    outlineWidth: 1,
    glowIntensity: 0,
    transform: 'arch',
    shadow: 'offset',
  },
  chrome: {
    fillColor: '#CCCCCC',
    gradientColor: '#999999',
    outlineColor: '#000000',
    outlineWidth: 2,
    glowIntensity: 4,
    transform: 'straight',
    shadow: 'perspective',
    bevel: 'convex',
  },
  rainbow: {
    fillColor: '#FF00FF',
    gradientColor: '#00FFFF',
    outlineColor: '#FFFFFF',
    outlineWidth: 2,
    glowIntensity: 10,
    transform: 'wave',
    shadow: 'offset',
  },
  sunset: {
    fillColor: '#FF6B35',
    gradientColor: '#E74C3C',
    outlineColor: '#C0392B',
    outlineWidth: 1,
    glowIntensity: 8,
    transform: 'curve',
    shadow: 'offset',
  },
  ocean: {
    fillColor: '#0099FF',
    gradientColor: '#00CCFF',
    outlineColor: '#004466',
    outlineWidth: 2,
    glowIntensity: 7,
    transform: 'curveUp',
    shadow: 'perspective',
  },
  forest: {
    fillColor: '#228B22',
    gradientColor: '#32CD32',
    outlineColor: '#0B4D0B',
    outlineWidth: 1.5,
    glowIntensity: 5,
    transform: 'straight',
    shadow: 'offset',
  },
  purple: {
    fillColor: '#9D4EDD',
    gradientColor: '#C77DFF',
    outlineColor: '#5A189A',
    outlineWidth: 2,
    glowIntensity: 9,
    transform: 'arch',
    shadow: 'perspective',
  },
  pink: {
    fillColor: '#FF1493',
    gradientColor: '#FF69B4',
    outlineColor: '#C71585',
    outlineWidth: 1.5,
    glowIntensity: 10,
    transform: 'wave',
    shadow: 'offset',
  },
  silver: {
    fillColor: '#E8E8E8',
    gradientColor: '#C0C0C0',
    outlineColor: '#808080',
    outlineWidth: 1.5,
    glowIntensity: 3,
    transform: 'straight',
    shadow: 'perspective',
    bevel: 'convex',
  },
  electric: {
    fillColor: '#00FFFF',
    gradientColor: '#7700FF',
    outlineColor: '#00FF00',
    outlineWidth: 2,
    glowIntensity: 14,
    transform: 'straight',
    shadow: 'none',
  },
  crystal: {
    fillColor: '#87CEEB',
    gradientColor: '#B0E0E6',
    outlineColor: '#5F9FBF',
    outlineWidth: 2,
    glowIntensity: 6,
    transform: 'inflate',
    shadow: 'offset',
  },
  emerald: {
    fillColor: '#50C878',
    gradientColor: '#00AA55',
    outlineColor: '#0B5F3C',
    outlineWidth: 2,
    glowIntensity: 7,
    transform: 'straight',
    shadow: 'perspective',
    bevel: 'softRound',
  },
  rose: {
    fillColor: '#B76E79',
    gradientColor: '#D4A5A5',
    outlineColor: '#8B6B6B',
    outlineWidth: 1.5,
    glowIntensity: 4,
    transform: 'curve',
    shadow: 'offset',
  },
  magma: {
    fillColor: '#FF4500',
    gradientColor: '#8B0000',
    outlineColor: '#FFFF00',
    outlineWidth: 2,
    glowIntensity: 11,
    transform: 'wave',
    shadow: 'offset',
  },
  aqua: {
    fillColor: '#00FFFF',
    gradientColor: '#00CED1',
    outlineColor: '#008B8B',
    outlineWidth: 2,
    glowIntensity: 8,
    transform: 'straight',
    shadow: 'offset',
  },
  sunset_gradient: {
    fillColor: '#FF7F50',
    gradientColor: '#FF1493',
    outlineColor: '#FF69B4',
    outlineWidth: 1.5,
    glowIntensity: 9,
    transform: 'archDown',
    shadow: 'perspective',
  },
  neon_pink: {
    fillColor: '#FF10F0',
    gradientColor: '#FF006E',
    outlineColor: '#FFFFFF',
    outlineWidth: 1.5,
    glowIntensity: 12,
    transform: 'wave',
    shadow: 'none',
  },
  dark_mode: {
    fillColor: '#1A1A2E',
    gradientColor: '#16213E',
    outlineColor: '#E94560',
    outlineWidth: 2,
    glowIntensity: 5,
    transform: 'straight',
    shadow: 'offset',
  },
  bronze: {
    fillColor: '#CD7F32',
    gradientColor: '#8B4513',
    outlineColor: '#3E2723',
    outlineWidth: 2,
    glowIntensity: 4,
    transform: 'straight',
    shadow: 'perspective',
    bevel: 'softRound',
  },
  copper: {
    fillColor: '#B87333',
    gradientColor: '#996633',
    outlineColor: '#654321',
    outlineWidth: 1.5,
    glowIntensity: 5,
    transform: 'arch',
    shadow: 'offset',
  },
  gradient_blue_purple: {
    fillColor: '#4169E1',
    gradientColor: '#8A2BE2',
    outlineColor: '#000080',
    outlineWidth: 2,
    glowIntensity: 8,
    transform: 'wave',
    shadow: 'perspective',
  },
  gradient_green_yellow: {
    fillColor: '#00FF00',
    gradientColor: '#FFFF00',
    outlineColor: '#228B22',
    outlineWidth: 1.5,
    glowIntensity: 9,
    transform: 'straight',
    shadow: 'offset',
  },
  gradient_red_orange: {
    fillColor: '#FF0000',
    gradientColor: '#FF8C00',
    outlineColor: '#DC143C',
    outlineWidth: 1.5,
    glowIntensity: 10,
    transform: 'wave',
    shadow: 'offset',
  },
  lava: {
    fillColor: '#FF3D00',
    gradientColor: '#FF0000',
    outlineColor: '#FFFF00',
    outlineWidth: 2,
    glowIntensity: 12,
    transform: 'inflate',
    shadow: 'offset',
  },
  aurora: {
    fillColor: '#00FF88',
    gradientColor: '#00FFFF',
    outlineColor: '#00FF00',
    outlineWidth: 2,
    glowIntensity: 11,
    transform: 'wave',
    shadow: 'none',
  },
  cyber: {
    fillColor: '#00FF00',
    gradientColor: '#00FFFF',
    outlineColor: '#FF00FF',
    outlineWidth: 1.5,
    glowIntensity: 13,
    transform: 'straight',
    shadow: 'none',
  },
  moss: {
    fillColor: '#6B8E23',
    gradientColor: '#556B2F',
    outlineColor: '#2F4F2F',
    outlineWidth: 1,
    glowIntensity: 3,
    transform: 'straight',
    shadow: 'offset',
  },
  midnight: {
    fillColor: '#00008B',
    gradientColor: '#191970',
    outlineColor: '#FFFFFF',
    outlineWidth: 2,
    glowIntensity: 4,
    transform: 'arch',
    shadow: 'perspective',
  },
  candy: {
    fillColor: '#FFB6C1',
    gradientColor: '#FFC0CB',
    outlineColor: '#FF1493',
    outlineWidth: 1.5,
    glowIntensity: 6,
    transform: 'wave',
    shadow: 'offset',
  },
  marble: {
    fillColor: '#F0F8FF',
    gradientColor: '#D3D3D3',
    outlineColor: '#696969',
    outlineWidth: 2,
    glowIntensity: 2,
    transform: 'straight',
    shadow: 'perspective',
  },
  vintage: {
    fillColor: '#DAA520',
    gradientColor: '#CD853F',
    outlineColor: '#8B4513',
    outlineWidth: 2,
    glowIntensity: 3,
    transform: 'arch',
    shadow: 'offset',
  },
  turquoise: {
    fillColor: '#40E0D0',
    gradientColor: '#48D1CC',
    outlineColor: '#008080',
    outlineWidth: 2,
    glowIntensity: 7,
    transform: 'curve',
    shadow: 'offset',
  },
  sapphire: {
    fillColor: '#0F52BA',
    gradientColor: '#0E4C92',
    outlineColor: '#001F6B',
    outlineWidth: 2,
    glowIntensity: 6,
    transform: 'straight',
    shadow: 'perspective',
    bevel: 'softRound',
  },
  coral: {
    fillColor: '#FF7F50',
    gradientColor: '#FF6347',
    outlineColor: '#DC143C',
    outlineWidth: 1.5,
    glowIntensity: 8,
    transform: 'wave',
    shadow: 'offset',
  },
  mint: {
    fillColor: '#98FF98',
    gradientColor: '#66CDAA',
    outlineColor: '#2E8B57',
    outlineWidth: 1.5,
    glowIntensity: 5,
    transform: 'straight',
    shadow: 'offset',
  },
  lavender: {
    fillColor: '#E6E6FA',
    gradientColor: '#D8BFD8',
    outlineColor: '#9370DB',
    outlineWidth: 1.5,
    glowIntensity: 4,
    transform: 'arch',
    shadow: 'offset',
  },
  neon_blue: {
    fillColor: '#0080FF',
    gradientColor: '#00BFFF',
    outlineColor: '#FFFFFF',
    outlineWidth: 2,
    glowIntensity: 12,
    transform: 'straight',
    shadow: 'none',
  },
  neon_purple: {
    fillColor: '#BF00FF',
    gradientColor: '#FF00FF',
    outlineColor: '#FFFFFF',
    outlineWidth: 2,
    glowIntensity: 12,
    transform: 'wave',
    shadow: 'none',
  },
  neon_orange: {
    fillColor: '#FF6500',
    gradientColor: '#FF8C00',
    outlineColor: '#FFD700',
    outlineWidth: 1.5,
    glowIntensity: 11,
    transform: 'straight',
    shadow: 'none',
  },
  retro: {
    fillColor: '#FF1493',
    gradientColor: '#FF69B4',
    outlineColor: '#FFB6C1',
    outlineWidth: 1,
    glowIntensity: 5,
    transform: 'curve',
    shadow: 'offset',
  },
  cyberpunk: {
    fillColor: '#00FF00',
    gradientColor: '#FF00FF',
    outlineColor: '#00FFFF',
    outlineWidth: 2,
    glowIntensity: 14,
    transform: 'skewDown',
    shadow: 'none',
  },
  steampunk: {
    fillColor: '#B8860B',
    gradientColor: '#8B4513',
    outlineColor: '#2F4F4F',
    outlineWidth: 2,
    glowIntensity: 2,
    transform: 'arch',
    shadow: 'offset',
    bevel: 'convex',
  },
  sparkle: {
    fillColor: '#FFD700',
    gradientColor: '#FFED4E',
    outlineColor: '#FFA500',
    outlineWidth: 2,
    glowIntensity: 10,
    transform: 'straight',
    shadow: 'perspective',
  },
  cosmic: {
    fillColor: '#1E3A8A',
    gradientColor: '#7C3AED',
    outlineColor: '#06B6D4',
    outlineWidth: 2,
    glowIntensity: 9,
    transform: 'wave',
    shadow: 'perspective',
  },
  tropical: {
    fillColor: '#FF4500',
    gradientColor: '#FFD700',
    outlineColor: '#00AA00',
    outlineWidth: 1.5,
    glowIntensity: 7,
    transform: 'wave',
    shadow: 'offset',
  },
  shadow_blue: {
    fillColor: '#1E90FF',
    gradientColor: '#00008B',
    outlineColor: '#000000',
    outlineWidth: 2,
    glowIntensity: 5,
    transform: 'straight',
    shadow: 'perspective',
  },
  shadow_red: {
    fillColor: '#DC143C',
    gradientColor: '#8B0000',
    outlineColor: '#000000',
    outlineWidth: 2,
    glowIntensity: 6,
    transform: 'arch',
    shadow: 'offset',
  },
  gradient_pink_purple: {
    fillColor: '#FF1493',
    gradientColor: '#DA70D6',
    outlineColor: '#9370DB',
    outlineWidth: 1.5,
    glowIntensity: 9,
    transform: 'wave',
    shadow: 'offset',
  },
  gradient_yellow_gold: {
    fillColor: '#FFFF00',
    gradientColor: '#FFD700',
    outlineColor: '#FF8C00',
    outlineWidth: 1.5,
    glowIntensity: 8,
    transform: 'straight',
    shadow: 'offset',
  },
  ice_blue: {
    fillColor: '#B0E0E6',
    gradientColor: '#87CEEB',
    outlineColor: '#4682B4',
    outlineWidth: 2,
    glowIntensity: 6,
    transform: 'curve',
    shadow: 'perspective',
  },
  ruby: {
    fillColor: '#E0115F',
    gradientColor: '#8B0000',
    outlineColor: '#FF1493',
    outlineWidth: 2,
    glowIntensity: 8,
    transform: 'straight',
    shadow: 'perspective',
    bevel: 'softRound',
  },
  pearl: {
    fillColor: '#FDEEF4',
    gradientColor: '#FFE4E1',
    outlineColor: '#C0C0C0',
    outlineWidth: 2,
    glowIntensity: 2,
    transform: 'straight',
    shadow: 'none',
  },
};

export const DEFAULT_TEXT_PROPERTIES = {
  text: 'Type Magic',
  fontSize: 16,
  fontFamily: 'Arial',
  fontWeight: 400,
  fontStyle: 'normal',
  textDecoration: 'none',
  textCase: 'none',
  transform: 'straight',
  
  // Fill settings
  fillType: 'solidColor',
  fillColor: '#000000',
  gradientColor: '#FF0000',
  gradientAngle: 45,
  
  // Outline settings
  outlineStyle: 'solid',
  outlineColor: '#000000',
  outlineWidth: 0,
  
  // Effects
  glowIntensity: 0,
  glowColor: '#FFFFFF',
  shadowType: 'none',
  shadowOffsetX: 4,
  shadowOffsetY: 4,
  shadowBlur: 6,
  shadowColor: '#000000',
  shadowOpacity: 0.5,
  
  // 3D & Reflection
  bevelType: 'none',
  reflectionType: 'none',
  
  // Text styling
  letterSpacing: 0,
  lineHeight: 1.2,
  wordSpacing: 0,
  fontVariantNumeric: 'normal',
  rotation: 0,
};

export const FONTS_FOR_TEXT = [
  // Classic Web-Safe Fonts
  'Arial Black',
  'Arial',
  'Times New Roman',
  'Courier New',
  'Georgia',
  'Trebuchet MS',
  'Verdana',
  'Impact',
  'Comic Sans MS',
  'Palatino Linotype',
  'Lucida Console',
  'Garamond',
  'Arial Narrow',
  'Book Antiqua',
  'Calibri',
  'Cambria',
  'Century Gothic',
  'Helvetica',
  'Tahoma',
  // Decorative Fonts
  'Algerian',
  'Baskerville Old Face',
  'Bauhaus 93',
  'Bell MT',
  'Bodoni MT',
  'Bookman Old Style',
  'Broadway',
  'Brush Script MT',
  'Californian FB',
  'Castellar',
  'Centaur',
  'Chiller',
  'Colonna MT',
  'Constantia',
  'Copperplate Gothic Bold',
  'Curlz MT',
  'Engravers MT',
  'Felix Titling',
  'Forte',
  'Freestyle Script',
  'Gabriola',
  'Gigi',
  'Goudy Old Style',
  'Harrington',
  'Jokerman',
  'Juice ITC',
  'Kristen ITC',
  'Kunstler Script',
  'Magneto',
  'Matura MT Script Capitals',
  'Mistral',
  'Modern No. 20',
  'Monotype Corsiva',
  'Niagara Engraved',
  'Niagara Solid',
  'OCR-A',
  'Old English Text MT',
  'Papyrus',
  'Perpetua',
  'Playbill',
  'Pristina',
  'Rage Italic',
  'Ravie',
  'Showcard Gothic',
  'Snap ITC',
  'Tempus Sans ITC',
  'Viner Hand ITC',
  'Vivaldi',
  'Vladimir Script',
  // Google Fonts - Sans Serif
  'Roboto',
  'Open Sans',
  'Lato',
  'Montserrat',
  'Inter',
  'Quicksand',
  'Poppins',
  'Nunito',
  'Dosis',
  'Raleway',
  'Ubuntu',
  'Titillium Web',
  'Proxima Nova',
  'Source Sans Pro',
  'Karla',
  'Oxanium',
  'Space Grotesk',
  'Manrope',
  'Work Sans',
  'Mulish',
  // Google Fonts - Serif
  'Playfair Display',
  'Merriweather',
  'Lora',
  'Crimson Text',
  'Libre Baskerville',
  'Cormorant Garamond',
  'EB Garamond',
  'Spectral',
  'Noto Serif',
  'Bitter',
  'PT Serif',
  'Abril Fatface',
  'Bodoni Moda',
  'Cinzel',
  'Rufina',
  // Google Fonts - Display & Fun
  'Bebas Neue',
  'Lobster',
  'Pacifico',
  'Bangers',
  'Anton',
  'Permanent Marker',
  'Shadows Into Light',
  'Indie Flower',
  'Amatic SC',
  'Caveat',
  'Dancing Script',
  'Architects Daughter',
  'Gloria Hallelujah',
  'Great Vibes',
  'Righteous',
  'Fredoka',
  'Outfit',
  'Sora',
  'Noto Sans',
  'Workbench',
  'VT323',
  'Comfortaa',
  'Varela Round',
  'Fredoka One',
  'Jost',
  'Lexend',
  'Montserrat Subrayada',
  'Oswald',
  'Secular One',
  'Alfa Slab One',
  'Lilita One',
  // Additional Stylish Fonts
  'Courier Prime',
  'IBM Plex Mono',
  'JetBrains Mono',
  'Inconsolata',
  'Playfair Display SC',
  'Bungee',
  'Orbitron',
  'Roboto Mono',
  'Source Code Pro',
  'Space Mono',
  // Modern Tech Fonts
  'Fira Sans',
  'Fira Mono',
  'Fira Code',
  'SFMono',
  'Menlo',
  // Handwriting & Script
  'Satisfy',
  'Tangerine',
  'Sacramento',
  'Allura',
  'Waiting for the Sunrise',
  'Covered by Your Grace',
  // Bold & Heavy
  'Black Ops One',
  'Press Start 2P',
  'Bungee Shade',
  'Bungee Outline',
  'Passion One',
  'Overpass',
  'Exo'
];

export const FONT_SIZES_TEXT = [
  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 36, 40, 44, 48, 54, 60, 66, 72, 80, 88, 96, 108, 120, 132, 144, 156, 168, 180, 200,
];

export const OUTLINE_WIDTHS = [0, 0.5, 1, 1.5, 2, 2.5, 3, 4, 5, 6];

export const SHADOW_OFFSETS = [
  { name: 'Offset Bottom Right', x: 4, y: 4 },
  { name: 'Offset Bottom Left', x: -4, y: 4 },
  { name: 'Offset Top Right', x: 4, y: -4 },
  { name: 'Offset Top Left', x: -4, y: -4 },
  { name: 'Offset Right', x: 6, y: 0 },
  { name: 'Offset Left', x: -6, y: 0 },
  { name: 'Offset Bottom', x: 0, y: 6 },
  { name: 'Offset Top', x: 0, y: -6 },
];
